- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/ContactCentreSvcApplication.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/FulfilmentsEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/message/ContactCentreEventPublisher.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/message/impl/ContactCentreEventPublisherImpl.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/EventService.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/EventServiceImpl.java
- src/main/resources/springintegration/broker.xml
- src/main/resources/springintegration/contact-centre-event-outbound.xml
- src/main/resources/springintegration/flows.xml
- src/main/resources/springintegration/main.xml
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/AddressEndpointTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/SmokeTest.java
Implement a Fanout Exchange and prove end-to-end flow of fulfilment request from the contact centre generating an event message on queues for any service listening from RM.
SpringIntegration standard pattern used in services has been added with a Fanout exchange and example RM.Queue1 and RM.Queue2 created. CaseEndpoint class has been added with an endpoint to request a fulfilment for a case by post. An EventService class has been added to place any logic required to map types of event and Publisher to publish the event to the exchange.
Unit tests have not been created until exact business requirements and integration with RM is understood when this functionality can be refactored and expanded to meet the requirement.
Change the application.yml Rabbitmq port to that where you are running …
> CR-89 Fanout Exchange implementation to prove integration with RM

- pom.xml
This change uses the latest api project which has the correct serialisation of the uprn field. This is now output as a string:
```
$ curl -s -H "Content-Type: application/json" --user $CC_USERNAME:$CC_PASSWORD "$CC/cases/9347a654-4f13-11e9-8647-d663bd873d93?case-events=true" | jq | head -15
{
"id": "9347a654-4f13-11e9-8647-d663bd873d93",
"caseRef": "123123",
"caseType": "HH",
"createdDateTime": "2019-04-14T13:45:26.564+01:00",
"addressLine1": "Napier House",
"addressLine2": "11 Park Street",
"addressLine3": "Parkhead",
"townName": "Glasgow",
"region": "E",
"postcode": "G1 2AA",
"uprn": "1347459999",
"caseEvents": null
}
```
> CR289 Use latest api to get the uprn being serialiased as a string.

- README.md
- pom.xml
This CR fixes the bug reported by Serco. 
404 errors were being reported in the body of a http response but the status code for the http request itself would be 500 instead of 404.
For details on the bug report see: https://collaborate2.ons.gov.uk/jira/browse/CR-314
The rest of this pull request reuses the pull request text for the actual fix to the RestClient:
This pull request covers 3 fixes:
1) No top level exception catching for the exceptions thrown during rest calls. So the, say, 404 status got mapped to a generic 500.
2) RestClient method for getResources (not getResource method) had error handling that didn't match a real server. The getResources() is now delegating to getResource().
3) Test failure due to the getResource handling of 204 errors. Now throwing exception for null …
> Cr314 report not found errors as 404

- pom.xml
Use latest common service for...
Minor improvements to fix:
- More logging done at warning level instead of error level.
- Improved text visible to external caller on 404 error.
> CR314 Using latest common for cleaned up error reporting

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java
This removes personal contact details (name, phone number, etc) for a refusal.
This is a temporary change for the 2019 rehearsal.
I've commented out the code which was setting the personal contact details. Similar change also done in the unit test. The start and end of the commented out code has been marked, and to aid future tracking includes 'CR-416'. 
Run the unit tests. I have also manually tested this service. and examined the event published to rabbit. 
See: https://collaborate2.ons.gov.uk/jira/browse/CR-416
> CR-416 Commented out code which sets the personal details for a refusal

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/AddressServiceClientServiceImpl.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/model/AddressIndexResponseDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/model/AddressIndexSearchResultsDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/model/PostcodeSearchResponseDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/AddressIndexSettings.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/AddressService.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImpl.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressIndex/AddressServiceClientServiceImplTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImplTest.java
- src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/client/addressIndex/AddressServiceClientServiceImplTest.testUPRNQueryProcessing.AddressIndexSearchResultsDTO.json
- src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImplTest.testUPRNQueryProcessing.AddressIndexSearchResultsDTO.json
Add the ability to search the remote Address Index (AI) service by UPRN. This is added to the service layer but not exposed directly through an endpoint, being utilised in later business flows.
Addition of uprnQuery to AddressService interface. The JSON response from AI for postcode and address string searches are the same. The JSON response for a UPRN search is very similar, but where only one, or no address can be returned for a UPRN the "addresses" array is renamed "address" and becomes a JSON object rather than array. The "offset", "limit" and "total" attributes are also removed from the JSON as no longer relevant. Rather than introduce another set of response objects for these minor differences and the extra code entailed I took the design decision to accommodate them simply in the …
> Cr 644 search address index by uprn

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java
FormType no longer hard coded as part of the JWE token payload but passed in to the method signature as part of the client request to create the JWE token.
FormType now returned in request to case service client and passed in request to EqLaunchService method to create  JWE token.
Unit tests amended to use passed in value. 
Can be tested running mock case api service, contact centre service and rabbitMQ locally and using Postman to hit contact centre launch URL e.g.
//localhost:8171/cases/03f58cb5-9af4-4d40-9d60-c124c5bddf09/launch?agentId=1111&individual=true
> Cr 755 pass form type to eq

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/FulfilmentsEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/FulfilmentsService.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/FulfilmentsServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/FulfilmentsEndpointTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/FulfilmentServiceImplTest.java
This  change is required to allow the contact centre service to use the latest version (1.0.1) of the product reference library and to meet the following requirements from card CR-737:
The GET /fulfilments endpoint currently allows the result list to be filtered by optional request params for caseType and region.
See swagger spec in GH census-contact-centre-service-api/swagger.yml
We need to additionally support filtering by the same method, by :
productGroup
individual (true|false)
(singular) deliveryChannel (SMS|POST)
Valid productGroups can be seen in the CC swagger spec, and in the census-int-product-reference v1.0.1
This will need to use the 1.0.1 version of the product reference library, refactored to allow for individual (true|false) and multiple case types
Also ensure that the …
> Update methods with new product reference fields

- pom.xml
- src/main/resources/application.yml
Due to a serious threading bug with Jetty RHSVC we have decided to switch from Jetty to Undertow.
We considered using Tomcat but Undertow was able to service more requests from the same hardware so we went with that.
Pom updated to use undertow, and corresponding Undertow thread configuration added to the application.yml file.
This should be a purely internal change. Run the usual tests.
> CR-875 Use and configure Undertow

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/CaseDataRepository.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/impl/CaseDataRepositoryImpl.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointCaseLaunchTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java
Amendment to endpoint "cases/{caseId}/launch".  If RM Case Service does not return the case but a new skeleton case exists in the Contact Centre repository, i.e. a new skeleton case has been created by the Contact Centre for an address but the NewAddressReported event not actioned by RM, return HTTP status 202 Accepted - the request has been accepted but might or might not be acted upon.
CaseServiceImpl changed to throw CTPException with Fault.ACCEPTED_UNABLE_TO_PROCESS for required scenario.
Unit tests extended to cover required scenario. Has also been tested locally and will deploy to Dev.
> CR-812_Telephone_Capture_Accepted

- src/main/resources/application.yml
Some Spring boot properties have gone out of date, as spotted by @philwhiles .
This updates those properties, in particular the undertow and graceful shutdown properties (which sneakily changed between Spring Boot 2.3.0-RC1 and 2.3.0-RELEASE1).
> CR-991 update/correct out-of-date spring boot properties

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/CaseService.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java
The getCaseByCaseID endpoint now attempts to return the case from the cache if not available from the case service. 
It calls down to existing code to actually call the case service and do the cache read.
> CR-813 Allow use of cached case for getCaseByCaseID

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/AddressServiceClientServiceImpl.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/AddressIndexSettings.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressIndex/AddressServiceClientServiceImplTest.java
Add 'epoch' as a query string parameter to requests to Address Index, configured by environment variable.
Simple addition of "epoch"  in requests to Address Index from AddressServiceClientServiceImpl.
Unit tests amended to include epoch, test included without epoch set.
#Note
If required to query a particular Address Index dataset set the environment variable:
'ADDRESS_INDEX_SETTINGS_EPOCH={epoch required e.g. 72}'
The nomenclature of this environment variable is set by the application.yml group of settings to which it belongs. It is not quite consistent with those of RH UI e.g. 'ADDRESS_INDEX_EPOCH'.
> CR-795_AIMS_epoch_query_string_parameter

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/CCSvcBeanMapperTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplFulfilmentTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByCaseRefTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByIdTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByUprnTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTestBase.java
CR-992 requires that the handDelivery attribute from RM plays no part in our processing in CCsvc, including not determining the allowed delivery channels returned for a case, and not preventing any fulfilment operations.
- allowedDeliveryChannels are always SMS and POST
- fulfilment by POST now no longer returns a 400 when handDelivery flag is set 
- The CaseDTO has not changed. @philwhiles  requested that the handDelivery attribute remains despite us not using it.
- usual unit tests
- postman to endpoints, check allowedDeliveryChannels
- postman for fulfilment by POST will not return 400 for handDelivery case.
- note that CC cucumber had no tests that checked the allowed Delivery Channels were anything other than all channels, so there are no specific tests there.
> Cr 992 remove hand delivery

- pom.xml
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointRefusalTest.java
UPRNs generated for skeleton cases by RM have an additional leading digit, needing to allow for 13 digits.
POM dependencies changed to include new UniquePropertyReferenceNumber allowing for 13 digits.
CaseEndPointRefusalTest Unit Test changed to use 14 digit UPRN to illicit BadRequest response.
Contact centre cucumber tests updated and run against this image in census-integration-dev. 
Please release with contact centre cucumber update.
Framework: https://github.com/ONSdigital/census-int-common-service/pull/44
Contact centre service api: https://github.com/ONSdigital/census-contact-centre-service-api/pull/53
Contact centre cucumber: https://github.com/ONSdigital/census-contact-centre-cucumber/pull/47
> CR-1047 Extend UPRN validation to allow 13 digits

- pom.xml
This change uses the lastest RestExceptionHander from the framework. 
CCSvc will now explain why incorrect Json is being rejected.
> Cr 1062 improve json validation error messages

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplCaseInvalidateTest.java
Invalidate endpoint now looks for case in cache if not in RM.
Test cases extended.
> CR-1068 Invalidate endpoint looking in cache if not found by RM

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/cloud/CachedCase.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplCreateCaseForNewAddressTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByIdTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByUprnTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplModifyCaseTest.java
- src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/PackageFixture.CachedCase.json
This change basically fixes the bug exposed by:
1) Create cached case by getting a case by uprn.
2) Get case using the new case id, with 'caseEvents=true'. This would originally fail as the cached case would be created without any case events and the get code assumed that the cached case had a non null case events collection.
Cached case are now created with an empty case events collection. 
This fix has also been applied for cached cases which can be created through the new-case and modify-case endpoints.
Corresponding unit tests have been updated.
Cucumber tests also updated is it expected an empty caseEvents collection.
> Cr 1067 cached case failing due to empty events

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplCreateCaseForNewAddressTest.java
The CC service must not allow creation of a case where the caseType is CE and the region is N.
Along with similar guards in other endpoints, we must not allow Serco to request creation of new case using the POST /cases endpoint if the region is 'N' and the case Type is 'CE'
If they do submit that combo we should return a 400 BAD_REQUEST with the following message :
“All queries relating to Communal Establishments in Northern Ireland should be escalated to NISRA HQ”
Changes have been made, mainly to the CaseServiceImpl, so that the newCase endpoint will:
1. Check the value of the caseType and region that are held in the NewCaseRequestDTO.
3. If the caseType is "CE" and region is "N" then throw an exception and return a BAD_REQUEST response with the error message specified above.
Relevant …
> Cr 1070 - CC Service Must Not Allow Creation of Case where caseType CE and region N

- README.md
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
In the refusals endpoint, the swagger allows for flexibility over fields being present or not, because Serco may not be able to find the right case, or ion worse case scenario, we were down for a while, and they will send the refusal later.
The endpoint allows for case id of "UNKNOWN" in this case, and if they could not find the case, they may not be sure what the region is - hence the swagger allowing region to be null.
The current implementation does not meet the swagger spec re: region!
If region sent as null, we get a null pointer exception.
A small change has been made to simply check whether the region, which comes in from the RefusalRequestDTO, is null or not.
If the RefusalRequestDTO has a region that's null then the RespondentRefusalDetails will no longer attempt to have any …
> Cr 1084 Refusal To Handle Region If Null

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/CaseService.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/CaseServiceFixture.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/EndpointSecurityTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetUACTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplLaunchTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTestBase.java
Add endpoint for assisted digital operative to obtain a UAC for a case. 
New endpoint added for url path /cases/{caseId}/uac with query parameters String adLocationId and Boolean individual. Business logic in service layer identical to the endpoint to obtain a launch URL with JWT session parameter.  
Unit tests added to cover new functionality. Endpoint can be hit on running application with Postman or Curl. Deployed to Dev and run against present cucumber tests.
Kanban board task: https://collaborate2.ons.gov.uk/jira/browse/CR-809
census-contact-centre-service-api dependency: https://github.com/ONSdigital/census-contact-centre-service-api/pull/58
> CR-809_Add_AD_get_UAC_endpoint

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/CCSvcBeanMapper.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/cloud/CachedCase.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/CCSvcBeanMapperTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplCreateCaseForNewAddressTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByCaseRefTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByIdTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByUprnTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplModifyCaseTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTestBase.java
- src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/PackageFixture.CachedCase.json
- Previously, all cached cases in firestore had empty caseEvents, now CR-1111 requires that caseEvents are stored in the cachedCases, as retrieved (and filtered) from RM.
- a bug with the PUT (modify) endpoint has been fixed where the createdDateTime was not being updated.
- endpoints returning cachedCase information have been updated to ensure caseEvents are returned when required.
NOTE: there is a minor cucumber change that goes with this for testing empty caseEvents. This needs to be merged at the same time as the cucumber PR.
- as agreed with @philwhiles , filtering of caseEvents has been done early after retrieval from RM. This assists the implementation of this feature.
- As agreed with @philwhiles  , all CaseDTO and cachedCase caseEvents will always be populated with non-null …
> Cr 1111 put endpoint should cache events

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointRefusalTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/EndpointSecurityTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplReportRefusalTest.java
Following on from the **agentId** changes from string to integer in CC-API, changes are necessary here to fit.
Note that the **agentId** in the event publisher objects by agreement remain as strings.
See JIRA CR-1114.
This needs to merged at the same time as the CC-cuc PR https://github.com/ONSdigital/census-contact-centre-cucumber/pull/59
> Cr 1114 unrestricted agent

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/utility/Constants.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointRefusalTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/EndpointSecurityTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplReportRefusalTest.java
Changes:
- Deleted code which supported the 'unknown' case in the refusals endpoint.
- Changed caseId in the request to an actual UUID object instead of a String.
- Updated unit tests.
> Cr 1160 removed unknown from refusuals endpoint

- pom.xml
Just a pom update.
Ensure the latest version of event publisher is used, so there is no chance that out-of-date event structures are stored in firestore.
Tests pass in DEV.
> Cr 1065 play firestore events

- pom.xml
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/EndpointSecurityTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByIdTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplModifyCaseTest.java
- src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/PackageFixture.CachedCase.json
The EstabType has been update in census-int-common-service and also OTHER type has been modified to fix an existing bug. A new version of census-int-common-service has been released which is 0.0.66. Updating pom.xml to point to this new version.
Also some tests have been updated as they were using the EstabTypes which do not exist anymore after the update to the EstabType enum.
For more details on the changes in census-int-common-service please have a look at https://collaborate2.ons.gov.uk/jira/browse/CR-1208.
> CR-1208 | Pointing to the new release version of census-int-common-service

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplModifyCaseTest.java
Send an address type changed event for a change of HH to SPG or vice versa. Previously sent address changed event.
CaseServiceImpl  removal of xor operator logic and replaced with simple comparison of requested CaseType to existing CaseType.
Unittests amended for HH and SPG change.   
Cucumber tests run for contact centre service.
https://collaborate2.ons.gov.uk/jira/browse/CR-1201
> CR-1202 Address type changed comparison

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/CCSPostcodesBean.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/AppConfig.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/CCSPostcodes.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpoint.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/CaseService.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointGetCcsCaseTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCcsCaseByPostcodeTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTestBase.java
The CR-744 task is to create a new endpoint, in the contact centre sevice, which will allow Serco staff to search for a CCS (Census Coverage Survey) case by postcode.
Serco will not be able to find the CCS cases that RM creates using the usual UPRN endpoint; RM have implemented a new endpoint in the Case API service:
@GetMapping(value = "/ccs/postcode/{postcode}")
public List<CaseContainerDTO> findCCSCasesByPostcode(
@PathVariable("postcode") String postcode,
@RequestParam(value = "caseEvents", required = false, defaultValue = "false")
boolean caseEvents);
The new contact centre service endpoint is slightly different to the existing GET case endpoints in the CC:
- This endpoint does NOT create a cached case - it cannot as it does not have the details required
- This endpoint first checks …
> Cr 744 - create endpoint to allow Serco staff to search for a CCS case by postcode

- src/main/resources/logback.xml
This change replicates the minor changes to RH Svc logback.xml (already merged) to prevent the omission of certain logging entries in the CLOUD profile.
> CR-1247 modify cloud logback config so it doesn't omit log entries

- pom.xml
To use latest version of Product Reference Library
Updated POM to use latest version of Product Reference library.
https://collaborate2.ons.gov.uk/jira/browse/CR-1191
> CR-1191 pom changed to refer latest version of Product Reference Library

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/AppConfig.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/EqConfig.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplLaunchTest.java
This is changed is required as CC service needs to send the passPhrase (SALT) to EQ launcher to encrypt the response Id
A new property is added to application yaml and same is passed to EQ Launcher
AppConfig changed : added a new attribute.
https://collaborate2.ons.gov.uk/jira/browse/CR-1205
> CR-1205 Changed for new EQ launcher version

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByUprnTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplModifyCaseTest.java
- src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/PackageFixture.CaseContainerDTO.json
Disallow CC to set estab type to OTHER if cases in RM or Cache is already existing establishment. 
The pre-existing Establishment Type cannot be changed to OTHER
Case Service is changed to add a check if there any establishment exists then it can not be changed to OTHER
Run put/cases endpoint with estabType as OTHER then if pre existing establishment is not OTHER it should throw BAD REQUEST with error message  "The pre-existing Establishment Type cannot be changed to OTHER"
https://collaborate2.ons.gov.uk/jira/browse/CR-1284
> CR-1284 Disallow estab type OTHER is already establishment exists

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/AddressServiceClientServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressIndex/AddressServiceClientServiceImplTest.java
A downstream API has additional requirements for requests now.
Requests to /addresses and /addresses/postcode/{postcode} in AI now have a includeauxiliarysearch query param which we need to pass.
The relevant unit tests have been updated.
https://collaborate2.ons.gov.uk/jira/browse/CR-1107
> Adding a new query parameter to two calls

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/AddressServiceClientServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressIndex/AddressServiceClientServiceImplTest.java
The CR-1443 ticket describes the task as follows:
AIMs inform us that to ensure we get a fuller list of results from /addresses when calling AI using the 'includeauxiliarysearch' request param, we should use 'matchthreshold=0'.
This is only required for using the AI /addresses and NOT when using /addresses/postcode
The searchByAddress method in AddressServiceClientServiceImpl has been modified so that it now includes matchthreshold=0 as described above. 
Two JUnit tests have also been modified to check the new parameter. These are:
1. testAddressQueryProcessing()
2. testAddressQueryProcessingNoEpoch()
Run rabbitmq, the mock case service, and this branch of the contact centre service.
Use Postman to send a GET request to the following URL: …
> CR-1443 Add matchthreshold Parameter to AI Call and Update Unit Tests

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplLaunchTest.java
Fixes a problem whereby CCS CE caseId's are not validated (rejected) in CCSvc, therefore passing them downstream to EQ to reject.
* validation to reject CCS CE caseID  when accessing launch endpoint with message as in JIRA
* remove misleading region validation (introduced in CR-907)
* it is agreed that the validation code, which is reused by the AD get UAC for caseId endpoint, is OK to be shared , since the AD endpoint will never handle CCS cases.
* go to CCSVc launch  endpoint with CaseId that is CCS and CE - should get 404 with message as in JIRA
https://collaborate2.ons.gov.uk/jira/browse/CR-1479
> Cr 1479 reject invalid ccs ce questionnaire

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplReportRefusalTest.java
Fix a bug where optional field that is not supplied (UPRN) causes an NPE , and an error back to caller, when it should succeed.
- UPRN access guarded by check for null
- unit tests updated.
https://collaborate2.ons.gov.uk/jira/browse/CR-1630
> CR-1630 accept null UPRN for refusal endpoint

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplLaunchTest.java
Bug fix.
The previous implementation for CR-1479 put the CE + CCS check after the call to get the QID  , so it fails just the same from the call to RM. 
This fix moves the check ahead of the call to get the QID.
> CR-1479 move validation ahead of call to get questionnaireId

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByUprnTest.java
RM rabbit events need to receive EstabType known code,  not mixed case as sometimes we have been sending (originating from AIMS).
Fix estabType published for NEW_ADDRESS_REPORTED event
https://collaborate2.ons.gov.uk/jira/browse/CR-1692
> CR-1692 make sure EstabType has known code for published event

- pom.xml
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/AddressEndpointTest.java
This change uses the latest CC API which has updated regex to block BFPO postcodes.
Changes:
- Added unit test to prove that BFPO postcodes are rejected.
- Unit test for BF postcodes which were temporarily added (also rejected)
- Fixed existing bug in unit tests
> Cr 1795 cc bf postcodes

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplLaunchTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplModifyCaseTest.java
A bug in the code where region returned from RM needs to be stripped of trailing characters and uppercase in order to compare with our normal Region names (eg "N" for northern ireland).  This has allowed us to skip a validation check and send invalid launch combinations to EQ.
This is the fix
- Use existing region converter , updated to ensure upper-case
- enhanced unit tests
- you will need case details coming from RM (or case simulator) with a region that is Northern Ireland with trailing chars, eg "N123" and CE
- Try to launch it via CCSvc with individual=false
- If the fix is in place then validation should return correct error message, otherwise it will go through to EQ to fail.
https://collaborate2.ons.gov.uk/jira/browse/CR-1810
> Cr 1810 prevent invalid ni ce launches

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
Improve logging for region lookup so that we can use the logging to find out how often Serco attach the wrong region, etc.
> Cr 1812 improve logging for region override on new case

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/AddressServiceClientServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressIndex/AddressServiceClientServiceImplTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/AddressEndpointTest.java
- Avoid failed call to AIMS due to lots of trailing white space
- restrict address search input to 250 chars in line with swagger
- pick up latest CCAPI to enforce 250 limit
- trim input before sending to AIMS
- unit tests
- unit tests
- postman on address search endpoint. Try long inputs or ones with surrounding white space.
https://collaborate2.ons.gov.uk/jira/browse/CR-1814
> Cr 1814 fix trailing spaces

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByCaseRefTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByIdTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByUprnTest.java
CCSvc has seen lots of EstabType NPE's due to RM having null EstabType ,  and these are increasing due to Field Service activity. This code provides guards and an adaption described in CR-1827 / CR-1773.
Check for EstabType Null from RM and ensure correct adaption done.
> CR-1827 guard against null EstabType from RM which caused NPEs

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplModifyCaseTest.java
Still getting EstabType.forCode NPE in CCSvc , but via the modifyCase path. 
- added unit tests
- tolerate null estabType from RM, such that the modify operation can set EstabType.OTHER when null in RM.
- unit tests
- manually, need to find an RM case with estabType of null, and try the modify endpoint with EstabType OTHER. Should work (previously would fail with NPE)
- cucumber tests 
https://collaborate2.ons.gov.uk/jira/browse/CR-1841
> Cr 1841 more estab type npe fixes

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplCreateCaseForNewAddressTest.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetCaseByUprnTest.java
CR-1823 documents a problem where AIMS has a mismatch of addressType and estabType. This causes some problems when Serco calls the "get Case by UPRN" endpoint where the case is not in RM, causing cases to be created with invalid combination of data, in particular the addressLevel. See CR-1823 for more information.
- Change the code setting the addressLevel for publishing a "New Address Reported" event to rely on CaseType rather than EstabType.
- update unit tests for get-case-by-uprn and additional unit tests for mismatching AIMS data
- update unit tests for create new address path. The unit tests were replicating the implementation logic that we have changed, so I changed the unit tests to not do that. Note that the problem would not occur through the Create New address endpoint since …
> Cr 1823 address level determined by case type
