ONSdigital/census-contact-centre-service

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/AddressEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/AddressService.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImpl.java

Adding fake endpoints for:
- /addresses/uprn
- /version

CR180 Added fake endpoints for /addresses/uprn update and also /version

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/AddressEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImplTest.java

Fixes count field in address results
Added apiVersion to /version response

Fix count in address query responses

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/caseservice/CaseServiceClientServiceImpl.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/CaseServiceSettings.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/CaseService.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/main/resources/application.yml
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/client/caseService/CaseServiceClientServiceImplTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/client/caseService/CaseServiceClientServiceImplTest.CaseContainerDTO.json

Implemented the the contact centre get case by case reference endpoint. 
This is very similar to the get case by case id endpoint, and mostly delegates it's work to the case service.
Unit tests have been added to test the new code. 
See: https://collaborate2.ons.gov.uk/jira/browse/CR-87

Cr87 retrieve case by case ref

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/ContactCentreSvcApplication.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/caseservice/CaseServiceClientServiceImpl.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/CaseServiceSettings.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/AddressEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/FulfilmentsEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/CaseService.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/EventService.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/main/resources/application.yml
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/client/caseService/CaseServiceClientServiceImplTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/EndpointSecurityTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/client/caseService/CaseServiceClientServiceImplTest.CaseContainerDTO.json
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.CaseContainerDTO.json

This pull request is for the implementation of the get case by UPRN endpoint.
Fake implementation replaced with code that makes a http call to the case service.
Run all unit tests..
See: https://collaborate2.ons.gov.uk/jira/browse/CR-85

CR85 First potentially working version of get case by UPRN

---

pom.xml

Using latest api project as that has a fix for the serialisation of the uprn field.

Cr289 add uprn to case responses

---

pom.xml

This pull request includes 2 changes:
- CR-550 to reduce the amount of chatter in logs. Reduces validation failures from error to warn level.
- CR-541 Product reference. Removed large print questionnaire.

Cr 550 reduce log level for validation failures

---

pom.xml
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointAppointmentTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointRefusalTest.java
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointAppointmentTest.json
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointFulfilmentSMSTest.json
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointRefusalTest.json
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointUnresolvedFulfilmentSMSTest.json

CR-648 fix questionnaire uac

---

pom.xml

Remove case state

---

pom.xml

Product ref lib has been updated to first 2021 business baseline
tested in dev

CR-749 product ref update

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpoint.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/FulfilmentsEndpointTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/FulfilmentServiceImplTest.java

Product lib 1.0.4 (reflecting business products version 2.3)
fulfilment language is  no more

CR-870 products update

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/CaseServiceFixture.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointCaseLaunchTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java

A couple of validation messages for the launch endpoint.

CR-907 invalid launch combination validation

---

pom.xml

Upgrade of contactcentreserviceapi required -> v98

Updated Contact-centre-service-api dependency

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/VersionEndpoint.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/VersionEndpointTest.java

/version endpoint keeps getting forgotten about. This code means you can forget about it and it returns the right thing.
Uses Snake Yaml.

CR-000 automatically get swagger version from CCAPI swagger current

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java

CR-1046 EQ launch url now RH URL

---

pom.xml

Move to Product release v2.5.
Cucumber tests can be run in Dev or locally. Must be released with contact centre cucumber tests product update below.
Product Reference: https://github.com/ONSdigital/census-int-product-reference/pull/11
Cucumber Tests: https://github.com/ONSdigital/census-contact-centre-cucumber/pull/44

CR-1013 Products release v2.5

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java

CR-1046 url tweak

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/EqConfig.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/main/resources/application.yml
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTest.java

CR-1046 enhance eq url to allow path from properties

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplLaunchTest.java

Use FormType "C" instead of "CE"

Cr 1044 form type c

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplModifyCaseTest.java

CR-973 set allowedDeliveryChannels on PUT CaseDTO response

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointRefusalTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/EndpointSecurityTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplReportRefusalTest.java
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpointRefusalTest.json

Update fields in refusal request

Cr 1063 upadate fields for refusal recieved

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/model/AddressIndexAddressCensusDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/model/AddressIndexAddressDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImpl.java
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImplTest.AddressIndexSearchResultsDTO.current.json
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImplTest.AddressIndexSearchResultsDTO.somehistoric.json

Move some fields for AI responses into 'census' object:
- censusAddressType
- censusEstabType
- countryCode

CR-1185 Moved some fields to new census object

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/model/AddressIndexAddressCensusDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImpl.java
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImplTest.AddressIndexSearchResultsDTO.current.json
src/test/resources/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImplTest.AddressIndexSearchResultsDTO.somehistoric.json

Corrected census field names to match what AI actually use.

CR-1185 Corrected field names below census to match what AI actually use

---

pom.xml
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/AddressEndpointTest.java

To refer latest version of CC Service API
pom.xml changed to refer latest version of CC Service API
https://collaborate2.ons.gov.uk/jira/browse/CR-1167

CR-1167 changed pom for latest version of CC service api

---

pom.xml

Changed for latest version of EQ Launcher
pom.xml
https://collaborate2.ons.gov.uk/jira/browse/CR-1304

CR1304 Changed to latest version of EQ Launcher

---

pom.xml

CR-1258 | updating dependency version

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/CCSPostcodesBean.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/impl/CaseDataRepositoryImpl.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java

Improving logging so that it can be efficiently used for monitoring. For more info please see CR-1259

CR-1259 | improving logging for monitoring

---

pom.xml

CR-1267 | dependency version update

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/AppConfig.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/Fulfilments.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/FulfilmentsServiceImpl.java
src/main/resources/application.yml
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplFulfilmentTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/FulfilmentServiceImplTest.java

This change allows fulfilment codes to be withdrawn.
See original CR for the details.

Cr 1526 blacklist fulfilment codes

---

pom.xml

contact-centre-service-api has changed
Updated dependency for contact-centre-service-api - PostFulfilmentRequestDTO max field sizes and swagger changes
Run unit / cucumber tests

Cr 1605 change max field values for postal fulfilments

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/ContactCentreSvcApplication.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/AppConfig.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/config/MessagingConfig.java
src/main/resources/application.yml

Retry added to rabbit send.
Configured number of attempts
Essentially a copy of the code in RHSvc PR: https://github.com/ONSdigital/census-rh-service/pull/110  which has been merged.
https://collaborate2.ons.gov.uk/jira/browse/CR-1612

CR-1612 publish retry

---

README.md
pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/ContactCentreSvcApplication.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/client/addressindex/AddressServiceClientServiceImpl.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/CaseEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/AddressServiceImpl.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/main/resources/application.yml

Cr 1627 increase http connection pool size

---

pom.xml

update to latest eq-launcher version

Cr 1658 period id 2021

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/ContactCentreSvcApplication.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplLaunchTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplTestBase.java

CR-1666 adds performance improvement to token generation
- use latest eq-launcher; conform to altered API.

CR-1666 use faster eq launch token code

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplCreateCaseForNewAddressTest.java

fixes repeated serco issue with CE new case and null ceUsualresidents

Fixed NPE with CE and null ceUsualResidents

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/AddressEndpoint.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/endpoint/AddressEndpointTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplCreateCaseForNewAddressTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplGetUACTest.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplLaunchTest.java

Merge of :
CR-1760
CR-1765
CR-1774

Hotfix 001
